# Generated by Django 5.0 on 2023-12-18 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycircle_app', '0005_circle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
