# Generated by Django 5.0 on 2023-12-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycircle_app', '0006_alter_circle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='circle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='mycircle_app.circle'),
        ),
    ]
