# Generated by Django 5.0 on 2023-12-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycircle_app', '0010_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='user',
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='mycircle_app.profile'),
        ),
    ]
