# Generated by Django 5.0 on 2023-12-26 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycircle_app', '0011_remove_profilepicture_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='blank_img.png', upload_to='uploaded_background_pics/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_picture', to='mycircle_app.profile')),
            ],
        ),
    ]
