# Generated by Django 5.0 on 2023-12-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycircle_app', '0012_backgroundpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='img',
            field=models.ImageField(default='circle_default.png', upload_to='uploaded_circle_img/'),
        ),
    ]
