# Generated by Django 5.0 on 2024-01-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycircle_app', '0013_circle_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='type',
            field=models.TextField(blank=True, default='standard'),
        ),
    ]
